import { Language } from './types';

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    appName: 'HARDI STORE',
    dashboard: 'DASHBOARD',
    sales: 'SALES',
    inventory: 'INVENTORY',
    debts: 'DEBTS',
    settings: 'SETTINGS',
    totalSales: 'Total Sales',
    totalPurchases: 'Total Purchases',
    netBalance: 'Net Balance',
    today: 'Today',
    thisMonth: 'This Month',
    addSale: 'Record Sale',
    addPurchase: 'Record Item',
    date: 'Date',
    amount: 'Amount',
    currency: 'Currency',
    note: 'Note',
    productName: 'Item Name',
    quantity: 'Qty',
    cost: 'Total Cost',
    save: 'SAVE RECORD',
    search: 'Search ID/Name...',
    code: 'ID Code',
    actions: 'Actions',
    noData: 'No records found',
    exportData: 'Export Data',
    importData: 'Import Data',
    dangerZone: 'Danger Zone',
    clearAll: 'Wipe Database',
    confirmClear: 'Irreversible action. Confirm?',
    language: 'Language',
    recentTransactions: 'Latest Activity',
    exportSuccess: 'Export Complete',
    importSuccess: 'Database Restored',
    importError: 'Corrupt File',
    filterFrom: 'From',
    filterTo: 'To',
    usd: 'USD',
    iqd: 'IQD',
    items: 'items',
    // Debt Specific
    weOwe: 'We Owe Others',
    owedToUs: 'Owed To Us',
    personName: 'Person Name',
    phone: 'Phone',
    dueDate: 'Due Date',
    status: 'Status',
    paid: 'Paid',
    unpaid: 'Unpaid',
    partial: 'Partial',
    addDebt: 'New Debt Record',
    addPayment: 'Add Payment',
    remaining: 'Remaining',
    paymentHistory: 'Payment History',
    totalWeOwe: 'Total Payable',
    totalOwedToUs: 'Total Receivable',
    debtType: 'Debt Type',
    weOweLabel: 'We Owe (Payable)',
    owedToUsLabel: 'Owed To Us (Receivable)',
    analytics: 'Analytics Overview',
    // Stores & Theme
    storeSection: 'Select Section',
    storeClothes: 'Clothes Store',
    storeShoes: 'Shoes & Bags',
    theme: 'Appearance',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    accentColor: 'Accent Color'
  },
  ku: {
    appName: 'HARDI STORE',
    dashboard: 'داشبۆرد',
    sales: 'فرۆشتن',
    inventory: 'کۆگا',
    debts: 'قەرزەکان',
    settings: 'ڕێکخستن',
    totalSales: 'کۆی فرۆشتن',
    totalPurchases: 'کۆی کڕین',
    netBalance: 'باڵانس',
    today: 'ئەمڕۆ',
    thisMonth: 'ئەم مانگە',
    addSale: 'تۆمارکردنی فرۆشتن',
    addPurchase: 'تۆمارکردنی کڕین',
    date: 'بەروار',
    amount: 'بڕ',
    currency: 'جۆر',
    note: 'تێبینی',
    productName: 'ناوی کاڵا',
    quantity: 'ژمارە',
    cost: 'تێچوو',
    save: 'تۆمارکردن',
    search: 'گەڕان...',
    code: 'کۆد',
    actions: 'کردار',
    noData: 'داتا نییە',
    exportData: 'هەناردەکردن',
    importData: 'هێنانەناوەوە',
    dangerZone: 'ناوچەی مەترسی',
    clearAll: 'سڕینەوەی گشتی',
    confirmClear: 'دڵنیای؟',
    language: 'زمان',
    recentTransactions: 'دوایین چالاکیەکان',
    exportSuccess: 'سەرکەوتوو بوو',
    importSuccess: 'سەرکەوتوو بوو',
    importError: 'فایل هەڵەیە',
    filterFrom: 'لە',
    filterTo: 'بۆ',
    usd: 'دۆلار',
    iqd: 'دینار',
    items: 'دانە',
    // Debt Specific
    weOwe: 'قەرزی سەرمان',
    owedToUs: 'قەرزی سەریان',
    personName: 'ناوی کەس',
    phone: 'مۆبایل',
    dueDate: 'وادەی دانەوە',
    status: 'دۆخ',
    paid: 'دراوە',
    unpaid: 'نەدراوە',
    partial: 'بەشێک',
    addDebt: 'زیادکردنی قەرز',
    addPayment: 'دانەوەی پارە',
    remaining: 'ماوە',
    paymentHistory: 'مێژووی پارەدان',
    totalWeOwe: 'کۆی قەرزی ئێمە',
    totalOwedToUs: 'کۆی قەرزی خەڵک',
    debtType: 'جۆری قەرز',
    weOweLabel: 'ئێمە قەرزدارین',
    owedToUsLabel: 'خەڵک قەرزدارە',
    analytics: 'شیکاری داتا',
    // Stores & Theme
    storeSection: 'بەش',
    storeClothes: 'پۆشاک',
    storeShoes: 'پێڵاو و جانتا',
    theme: 'ڕوکار',
    lightMode: 'ڕووناک',
    darkMode: 'تاریک',
    accentColor: 'ڕەنگی سەرەکی'
  }
};

export const INITIAL_DATA = {
  sales: [],
  purchases: [],
  debts: []
};